mv libril.so ./2/libril.so 
mv libril-qc-1.so ./2/libril-qc-1.so 
mv libril-qcril-hook-oem.so ./2/libril-qcril-hook-oem.so 
mv libreference-ril ./2/libreference-ril 
mv libdiag.so ./2/libdiag.so 
mv liboncrpc.so ./2/liboncrpc.so 
mv libqmi.so ./2/libqmi.so 
mv libdsm.so ./2/libdsm.so 
mv libqueue.so ./2/libqueue.so 
mv libdll.so ./2/libdll.so 
mv libcm.so ./2/libcm.so 
mv libmmgsdilib.so ./2/libmmgsdilib.so 
mv libgsdi_exp.so ./2/libgsdi_exp.so 
mv libgstk_exp.so ./2/libgstk_exp.so 
mv libwms.so ./2/libwms.so 
mv libnv.so ./2/libnv.so 
mv libwmsts.so ./2/libwmsts.so 
mv libpbmlib.so ./2/libpbmlib.so 
mv libdss.so ./2/libdss.so 
mv libauth.so ./2/libauth.so
mv liboemcamera.so ./2/liboemcamera.so 
mv liboemcamera.so obj/lib/liboemcamera.so 
mv libmmjpeg.so ./2/libmmjpeg.so 
mv libmmipl.so ./2/libmmipl.so 
mv libOmxEvrcEnc.so ./2/libOmxEvrcEnc.so 
mv libOmxAacDec.so ./2/libOmxAacDec.so 
mv libOmxQcelpDec.so ./2/libOmxQcelpDec.so 
mv libOmxAmrEnc.so ./2/libOmxAmrEnc.so 
mv libOmxAdpcmDec.so ./2/libOmxAdpcmDec.so 
mv libOmxEvrcDec.so ./2/libOmxEvrcDec.so 
mv libOmxAmrDec.so ./2/libOmxAmrDec.so 
mv libOmxAmrwbDec.so ./2/libOmxAmrwbDec.so 
mv libOmxWmaDec.so ./2/libOmxWmaDec.so 
mv libOmxQcelp13Enc.so ./2/libOmxQcelp13Enc.so 
mv libOmxMp3Dec.so ./2/libOmxMp3Dec.so 
mv libOmxAmrRtpDec.so ./2/libOmxAmrRtpDec.so 
mv libOmxAacEnc.so ./2/libOmxAacEnc.so 
mv libmm-adspsvc.so ./2/libmm-adspsvc.so 
mv libomx_aacdec_sharedlibrary.so ./2/libomx_aacdec_sharedlibrary.so 
mv libomx_amrdec_sharedlibrary.so ./2/libomx_amrdec_sharedlibrary.so 
mv libomx_amrenc_sharedlibrary.so ./2/libomx_amrenc_sharedlibrary.so 
mv libomx_avcdec_sharedlibrary.so ./2/libomx_avcdec_sharedlibrary.so 
mv libomx_m4vdec_sharedlibrary.so ./2/libomx_m4vdec_sharedlibrary.so 
mv libomx_mp3dec_sharedlibrary.so ./2/libomx_mp3dec_sharedlibrary.so 
mv libomx_sharedlibrary.so ./2/libomx_sharedlibrary.so
mv libgsl.so ./2/libgsl.so 
