ifeq ($(TARGET_BOOTLOADER_BOARD_NAME),u8800)

LOCAL_PATH := $(call my-dir)

ifeq ($(BOARD_RECOVERY_CHARGEMODE),true)
include $(CLEAR_VARS)
LOCAL_MODULE := offmode_charge
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES_LOCAL
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_SRC_FILES := offmode_check.c
LOCAL_MODULE:= offmode_check
LOCAL_STATIC_LIBRARIES := libcutils libc libstdc++
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_MODULE_TAGS := eng
include $(BUILD_EXECUTABLE)
endif
endif
